package com.bayviewglen.firstFifty;

import java.math.BigInteger;

public class twoFibonacci {
	
	public static void main(String[] args) {

		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous
		 * two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * 
		 * By considering the terms in the Fibonacci sequence whose values do not exceed
		 * four million, find the sum of the even-valued terms.
		 */

		BigInteger ZERO = new BigInteger("0");
		
		int n = 10;
		BigInteger[] solutions = new BigInteger[n];
		BigInteger sum = new BigInteger("0");

		fibonacci(solutions, n);

		for (int i = 0; i < n; i++) {
			if (solutions[i].mod(new BigInteger("2")).equals(ZERO)) {
				System.out.print(solutions[i] + "  ");
			}
		}
		System.out.println();
		
		for (int i = 0; i < n; i++) {
			if (solutions[i].mod(new BigInteger("2")).equals(ZERO)) {
				sum = sum.add(solutions[i]);
			}
		}
		
		System.out.println("The sum of the first " + n + " terms in the Fibonacci sequence is: " + sum);

	}

	private static void fibonacci(BigInteger[] solutions, int n) {
		solutions[1] = new BigInteger("1");
		solutions[2] = new BigInteger("1");

		for (int i = 3; i < n; i++) {
			solutions[i] = solutions[i - 1].add(solutions[i - 2]);
		}
	}

}
