package com.bayviewglen.firstFifty;

import java.math.BigInteger;

public class twoFibonacci {

	public static void main(String[] args) {

		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous
		 * two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * 
		 * By considering the terms in the Fibonacci sequence whose values do not exceed
		 * four million, find the sum of the even-valued terms.
		 */

		int n = 33;
		long[] solutions = new long[n];
		long sum = 0;

		fibonacci(solutions, n);

		for (int i = 0; i < n; i++) {
			if (solutions[i] % 2 == 0) {
				System.out.print(solutions[i] + "  ");
			}
		}
		System.out.println();

		for (int i = 0; i < n; i++) {
			if (solutions[i] % 2 == 0) {
				sum += solutions[i];
			}
		}

		System.out.println("The sum of the first " + n + " terms in the Fibonacci sequence is: " + sum);

	}

	private static void fibonacci(long[] solutions, int n) {
		solutions[1] = 1;
		solutions[2] = 1;

		for (int i = 3; i < n; i++) {
			solutions[i] = solutions[i - 1] + solutions[i - 2];
		}
	}

}
